namespace SchoolErp.Shared.Localization;

/// <summary>
/// Portal UI strings. English is the source of truth; Telugu must cover every
/// key (unit-enforced). Pages not yet listed here simply stay English — add
/// keys as pages are localized. Lives in Shared so tests can verify coverage
/// without referencing the WASM project.
/// </summary>
public static class PortalStrings
{
    public static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // Chrome / navigation
        ["nav.dashboard"] = "Dashboard",
        ["nav.schools"] = "Schools",
        ["nav.academics"] = "Academics",
        ["nav.students"] = "Students",
        ["nav.admissions"] = "Admissions",
        ["nav.attendance"] = "Attendance",
        ["nav.exams"] = "Exams",
        ["nav.fees"] = "Fees",
        ["nav.homework"] = "Homework",
        ["nav.notices"] = "Notices",
        ["nav.transport"] = "Transport",
        ["nav.timetable"] = "Timetable",
        ["nav.teachers"] = "Teachers",
        ["nav.library"] = "Library",
        ["nav.hostel"] = "Hostel",
        ["nav.leave"] = "Leave",
        ["nav.messages"] = "Messages",
        ["nav.users"] = "Users & roles",
        ["nav.insights"] = "Insights",
        ["nav.subscription"] = "Subscription",
        ["nav.audit"] = "Audit log",
        ["chrome.myDevices"] = "My devices",
        ["chrome.security"] = "Security",
        ["chrome.signOut"] = "Sign out",
        ["chrome.darkMode"] = "Toggle dark mode",
        ["chrome.onAkshara"] = "on Akshara",

        // Login
        ["login.title"] = "Sign in",
        ["login.schoolCode"] = "School code",
        ["login.schoolCodeHelp"] = "Leave empty for platform (Super Admin) sign-in",
        ["login.emailOrPhone"] = "Email or phone",
        ["login.password"] = "Password",
        ["login.signIn"] = "Sign in",
        ["login.signingIn"] = "Signing in…",
        ["login.forgot"] = "Forgot password?",
        ["login.cannotReach"] = "Cannot reach the server. Is the API running?",

        // Dashboard
        ["home.title"] = "Dashboard",
        ["home.attendanceToday"] = "Attendance today",
        ["home.notMarked"] = "Not marked",
        ["home.activeStudentsSuffix"] = "active students",
        ["home.markedPresent"] = "of {0} marked present",
        ["home.feesThisMonth"] = "Fees collected this month",
        ["home.overdueBooks"] = "Overdue library books",
        ["home.activeStudents"] = "Active students",
        ["home.upcomingExams"] = "Upcoming exams",
        ["home.nothingScheduled"] = "Nothing scheduled ahead.",
        ["home.needsAttention"] = "Needs attention",
        ["home.pendingLeave"] = "Pending leave requests",
        ["home.unreadMessages"] = "Unread parent messages",
        ["home.openEnquiries"] = "Open admission enquiries",
        ["home.followUpsDue"] = "Enquiry follow-ups due",
        ["home.quickActions"] = "Quick actions",
        ["home.qaMarkAttendance"] = "Mark attendance",
        ["home.qaAdmitStudent"] = "Admit student",
        ["home.qaCollectFee"] = "Collect a fee",
        ["home.qaImport"] = "Import students",
        ["home.attendanceTrend"] = "Attendance — last 14 days",
        ["home.feeTrend"] = "Collections — last 14 days",
        ["home.noTrend"] = "No roll-call marked in the last 14 days.",
        ["home.birthdays"] = "Birthdays today",
        ["home.turns"] = "turns {0}",
        ["home.feesOutstanding"] = "Fees outstanding",
        ["home.smsCredits"] = "SMS credits",
        ["home.smsLow"] = "Running low — top up soon",
        ["home.subscriptionExpires"] = "Subscription expires {0}",


        // My day (teacher self-service)
        ["myday.title"] = "My day",
        ["myday.notTeacher"] = "This page is for teachers. Your account isn't linked to a staff record — ask your school admin to create your teacher login.",
        ["myday.periods"] = "Today's periods",
        ["myday.noPeriods"] = "No periods scheduled today.",
        ["myday.period"] = "Period",
        ["myday.subject"] = "Subject",
        ["myday.classSection"] = "Class",
        ["myday.time"] = "Time",
        ["myday.attendance"] = "Attendance",
        ["myday.marked"] = "Marked",
        ["myday.notMarked"] = "Not marked",
        ["myday.cover"] = "Cover",
        ["myday.markNow"] = "Mark attendance",
        ["myday.awaitingAttendance"] = "Sections awaiting attendance",
        ["myday.studentsTaught"] = "Students you teach",
        ["myday.pendingLeave"] = "Leave requests from your students",
        ["myday.marksBacklog"] = "Marks not entered",
        ["myday.noMarksBacklog"] = "Every paper of yours has marks.",
        ["myday.homeworkDue"] = "Homework due this week",
        ["myday.noHomework"] = "Nothing due in the next seven days.",
        ["myday.enterMarks"] = "Enter marks",
        ["myday.openTimetable"] = "My timetable",


        // Front office
        ["nav.frontOffice"] = "Front office",
        ["frontoffice.title"] = "Front office",
        ["frontoffice.visitors"] = "Visitors",
        ["frontoffice.gatePasses"] = "Gate passes",
        ["frontoffice.visitorName"] = "Visitor name",
        ["frontoffice.phone"] = "Phone",
        ["frontoffice.purpose"] = "Purpose",
        ["frontoffice.purposeParent"] = "Parent meeting",
        ["frontoffice.purposeAdmission"] = "Admission enquiry",
        ["frontoffice.purposeDelivery"] = "Delivery",
        ["frontoffice.purposeOfficial"] = "Official",
        ["frontoffice.purposeOther"] = "Other",
        ["frontoffice.whomToMeet"] = "Whom to meet",
        ["frontoffice.checkIn"] = "Check in",
        ["frontoffice.checkOut"] = "Check out",
        ["frontoffice.openOnly"] = "Still inside only",
        ["frontoffice.noVisitors"] = "No visitors logged.",
        ["frontoffice.pass"] = "Pass",
        ["frontoffice.inOut"] = "In / out",
        ["frontoffice.left"] = "Left",
        ["frontoffice.student"] = "Student",
        ["frontoffice.reason"] = "Reason",
        ["frontoffice.releasedTo"] = "Released to",
        ["frontoffice.issuePass"] = "Issue pass",
        ["frontoffice.markReturned"] = "Mark returned",
        ["frontoffice.returned"] = "Returned",
        ["frontoffice.noPasses"] = "No gate passes issued today.",
        ["frontoffice.gatePassHelp"] = "Issuing a pass sends the primary guardian a message that their child left early.",
        ["frontoffice.nameRequired"] = "Enter the visitor's name.",
        ["frontoffice.passRequired"] = "Pick a student and fill the reason and who is collecting them.",
        ["frontoffice.passIssued"] = "Gate pass issued; the guardian has been notified.",
        ["frontoffice.cannotReach"] = "Cannot reach the server.",
        ["frontoffice.studentsUnavailable"] = "Student list unavailable; gate passes need it.",


        // Inventory (school store)
        ["nav.inventory"] = "Store",
        ["inventory.title"] = "School store",
        ["inventory.search"] = "Search items",
        ["inventory.lowOnly"] = "Low stock only",
        ["inventory.addItem"] = "Add item",
        ["inventory.itemName"] = "Item",
        ["inventory.category"] = "Category",
        ["inventory.unit"] = "Unit",
        ["inventory.reorderLevel"] = "Reorder at",
        ["inventory.unitCost"] = "Unit cost",
        ["inventory.recordMovement"] = "Record movement",
        ["inventory.item"] = "Item",
        ["inventory.kind"] = "Movement",
        ["inventory.kindReceipt"] = "Received",
        ["inventory.kindIssue"] = "Issued",
        ["inventory.kindWriteOff"] = "Written off",
        ["inventory.kindAdjustment"] = "Counted",
        ["inventory.quantity"] = "Quantity",
        ["inventory.counterparty"] = "To / from",
        ["inventory.adjustmentHint"] = "A count sets the balance outright, it is not added.",
        ["inventory.stock"] = "Stock on hand",
        ["inventory.onHand"] = "On hand",
        ["inventory.register"] = "Store register",
        ["inventory.balance"] = "Balance",
        ["inventory.date"] = "Date",
        ["inventory.retired"] = "Retired",
        ["inventory.noItems"] = "No items yet.",
        ["inventory.noMovements"] = "No stock movements yet.",
        ["inventory.nameRequired"] = "Enter an item name.",
        ["inventory.itemRequired"] = "Pick an item first.",
        ["inventory.cannotReach"] = "Cannot reach the server.",


        // Shell chrome and navigation groups
        ["chrome.skipToContent"] = "Skip to main content",
        ["chrome.toggleNav"] = "Toggle navigation",
        ["chrome.mainNav"] = "Main navigation",
        ["chrome.account"] = "Account menu",
        ["chrome.language"] = "Change language",
        ["chrome.platform"] = "Platform",
        ["nav.myDay"] = "My day",
        ["nav.group.overview"] = "Overview",
        ["nav.group.academics"] = "Academics",
        ["nav.group.people"] = "People",
        ["nav.group.operations"] = "Operations",
        ["nav.group.communication"] = "Communication",
        ["nav.group.finance"] = "Finance",
        ["nav.group.administration"] = "Administration",
        ["error.pageTitle"] = "This page could not be displayed",
        ["error.pageBody"] = "Something went wrong while rendering this page. Your data has not been changed.",
        ["error.retry"] = "Try again",

        // Students
        ["students.title"] = "Students",
        ["students.export"] = "Export",
        ["students.import"] = "Import from Excel",
        ["students.admit"] = "Admit student",
        ["students.search"] = "Search name or admission no.",
        ["students.class"] = "Class",
        ["students.section"] = "Section",
        ["students.status"] = "Status",
        ["students.admissionNo"] = "Admission no.",
        ["students.name"] = "Name",
        ["students.roll"] = "Roll",
        ["students.none"] = "No students found. Admit the first one.",
        ["students.importTitle"] = "Bulk import from Excel",
        ["students.importHelp"] =
            "1. Download the template — it lists this school's classes and sections. " +
            "2. Fill one student per row. 3. Upload the file. Nothing is imported " +
            "unless every row is valid, so a half-filled school can never happen.",
        ["students.downloadTemplate"] = "Download template",
        ["students.uploadTemplate"] = "Upload filled template",
        ["students.importing"] = "Importing…",
        ["students.rowHeader"] = "Row",
        ["students.problemHeader"] = "Problem",
    };

    public static readonly IReadOnlyDictionary<string, string> Te = new Dictionary<string, string>
    {
        // Chrome / navigation
        ["nav.dashboard"] = "డాష్‌బోర్డ్",
        ["nav.schools"] = "పాఠశాలలు",
        ["nav.academics"] = "విద్యా వ్యవహారాలు",
        ["nav.students"] = "విద్యార్థులు",
        ["nav.admissions"] = "ప్రవేశాలు",
        ["nav.attendance"] = "హాజరు",
        ["nav.exams"] = "పరీక్షలు",
        ["nav.fees"] = "ఫీజులు",
        ["nav.homework"] = "హోంవర్క్",
        ["nav.notices"] = "ప్రకటనలు",
        ["nav.transport"] = "రవాణా",
        ["nav.timetable"] = "కాలపట్టిక",
        ["nav.teachers"] = "ఉపాధ్యాయులు",
        ["nav.library"] = "గ్రంథాలయం",
        ["nav.hostel"] = "వసతిగృహం",
        ["nav.leave"] = "సెలవులు",
        ["nav.messages"] = "సందేశాలు",
        ["nav.users"] = "వినియోగదారులు & పాత్రలు",
        ["nav.insights"] = "అంతర్దృష్టులు",
        ["nav.subscription"] = "చందా",
        ["nav.audit"] = "ఆడిట్ లాగ్",
        ["chrome.myDevices"] = "నా పరికరాలు",
        ["chrome.security"] = "భద్రత",
        ["chrome.signOut"] = "సైన్ అవుట్",
        ["chrome.darkMode"] = "డార్క్ మోడ్ మార్చండి",
        ["chrome.onAkshara"] = "అక్షరపై",

        // Login
        ["login.title"] = "సైన్ ఇన్",
        ["login.schoolCode"] = "స్కూల్ కోడ్",
        ["login.schoolCodeHelp"] = "ప్లాట్‌ఫారమ్ (సూపర్ అడ్మిన్) సైన్-ఇన్ కోసం ఖాళీగా వదలండి",
        ["login.emailOrPhone"] = "ఇమెయిల్ లేదా ఫోన్",
        ["login.password"] = "పాస్‌వర్డ్",
        ["login.signIn"] = "సైన్ ఇన్",
        ["login.signingIn"] = "సైన్ ఇన్ అవుతోంది…",
        ["login.forgot"] = "పాస్‌వర్డ్ మర్చిపోయారా?",
        ["login.cannotReach"] = "సర్వర్‌ను చేరుకోలేకపోతున్నాం. API నడుస్తోందా?",

        // Dashboard
        ["home.title"] = "డాష్‌బోర్డ్",
        ["home.attendanceToday"] = "ఈరోజు హాజరు",
        ["home.notMarked"] = "నమోదు కాలేదు",
        ["home.activeStudentsSuffix"] = "క్రియాశీల విద్యార్థులు",
        ["home.markedPresent"] = "{0} లో హాజరైనవారు",
        ["home.feesThisMonth"] = "ఈ నెల వసూలైన ఫీజులు",
        ["home.overdueBooks"] = "గడువు దాటిన గ్రంథాలయ పుస్తకాలు",
        ["home.activeStudents"] = "క్రియాశీల విద్యార్థులు",
        ["home.upcomingExams"] = "రాబోయే పరీక్షలు",
        ["home.nothingScheduled"] = "ముందుగా ఏమీ షెడ్యూల్ కాలేదు.",
        ["home.needsAttention"] = "దృష్టి అవసరం",
        ["home.pendingLeave"] = "పెండింగ్ సెలవు అభ్యర్థనలు",
        ["home.unreadMessages"] = "చదవని తల్లిదండ్రుల సందేశాలు",
        ["home.openEnquiries"] = "తెరిచి ఉన్న ప్రవేశ విచారణలు",
        ["home.followUpsDue"] = "గడువు వచ్చిన ఫాలో-అప్‌లు",
        ["home.quickActions"] = "త్వరిత చర్యలు",
        ["home.qaMarkAttendance"] = "హాజరు నమోదు",
        ["home.qaAdmitStudent"] = "విద్యార్థి ప్రవేశం",
        ["home.qaCollectFee"] = "ఫీజు వసూలు",
        ["home.qaImport"] = "విద్యార్థుల దిగుమతి",
        ["home.attendanceTrend"] = "హాజరు — గత 14 రోజులు",
        ["home.feeTrend"] = "వసూళ్లు — గత 14 రోజులు",
        ["home.noTrend"] = "గత 14 రోజుల్లో హాజరు నమోదు కాలేదు.",
        ["home.birthdays"] = "ఈరోజు పుట్టినరోజులు",
        ["home.turns"] = "{0} ఏళ్లు",
        ["home.feesOutstanding"] = "బాకీ ఉన్న ఫీజులు",
        ["home.smsCredits"] = "SMS క్రెడిట్లు",
        ["home.smsLow"] = "తక్కువగా ఉన్నాయి — త్వరలో టాప్-అప్ చేయండి",
        ["home.subscriptionExpires"] = "చందా గడువు {0}",


        // My day (teacher self-service)
        ["myday.title"] = "నా రోజు",
        ["myday.notTeacher"] = "ఈ పేజీ ఉపాధ్యాయుల కోసం. మీ ఖాతా సిబ్బంది రికార్డుతో అనుసంధానించబడలేదు — మీ పాఠశాల నిర్వాహకుడిని లాగిన్ సృష్టించమని అడగండి.",
        ["myday.periods"] = "ఈరోజు పీరియడ్లు",
        ["myday.noPeriods"] = "ఈరోజు పీరియడ్లు లేవు.",
        ["myday.period"] = "పీరియడ్",
        ["myday.subject"] = "సబ్జెక్ట్",
        ["myday.classSection"] = "తరగతి",
        ["myday.time"] = "సమయం",
        ["myday.attendance"] = "హాజరు",
        ["myday.marked"] = "నమోదైంది",
        ["myday.notMarked"] = "నమోదు కాలేదు",
        ["myday.cover"] = "ప్రత్యామ్నాయం",
        ["myday.markNow"] = "హాజరు నమోదు",
        ["myday.awaitingAttendance"] = "హాజరు నమోదు కావలసిన సెక్షన్లు",
        ["myday.studentsTaught"] = "మీరు బోధించే విద్యార్థులు",
        ["myday.pendingLeave"] = "మీ విద్యార్థుల సెలవు అభ్యర్థనలు",
        ["myday.marksBacklog"] = "నమోదు కాని మార్కులు",
        ["myday.noMarksBacklog"] = "మీ ప్రతి పేపర్‌కు మార్కులు ఉన్నాయి.",
        ["myday.homeworkDue"] = "ఈ వారం గడువు హోంవర్క్",
        ["myday.noHomework"] = "రాబోయే ఏడు రోజుల్లో ఏమీ లేదు.",
        ["myday.enterMarks"] = "మార్కులు నమోదు",
        ["myday.openTimetable"] = "నా కాలపట్టిక",


        // Front office
        ["nav.frontOffice"] = "ఫ్రంట్ ఆఫీస్",
        ["frontoffice.title"] = "ఫ్రంట్ ఆఫీస్",
        ["frontoffice.visitors"] = "సందర్శకులు",
        ["frontoffice.gatePasses"] = "గేట్ పాస్‌లు",
        ["frontoffice.visitorName"] = "సందర్శకుని పేరు",
        ["frontoffice.phone"] = "ఫోన్",
        ["frontoffice.purpose"] = "ప్రయోజనం",
        ["frontoffice.purposeParent"] = "తల్లిదండ్రుల సమావేశం",
        ["frontoffice.purposeAdmission"] = "ప్రవేశ విచారణ",
        ["frontoffice.purposeDelivery"] = "డెలివరీ",
        ["frontoffice.purposeOfficial"] = "అధికారిక",
        ["frontoffice.purposeOther"] = "ఇతర",
        ["frontoffice.whomToMeet"] = "ఎవరిని కలవాలి",
        ["frontoffice.checkIn"] = "చెక్ ఇన్",
        ["frontoffice.checkOut"] = "చెక్ అవుట్",
        ["frontoffice.openOnly"] = "లోపల ఉన్నవారు మాత్రమే",
        ["frontoffice.noVisitors"] = "సందర్శకుల నమోదు లేదు.",
        ["frontoffice.pass"] = "పాస్",
        ["frontoffice.inOut"] = "లోపలికి / బయటికి",
        ["frontoffice.left"] = "వెళ్లారు",
        ["frontoffice.student"] = "విద్యార్థి",
        ["frontoffice.reason"] = "కారణం",
        ["frontoffice.releasedTo"] = "ఎవరికి అప్పగించారు",
        ["frontoffice.issuePass"] = "పాస్ ఇవ్వండి",
        ["frontoffice.markReturned"] = "తిరిగి వచ్చినట్లు గుర్తించండి",
        ["frontoffice.returned"] = "తిరిగి వచ్చారు",
        ["frontoffice.noPasses"] = "ఈరోజు గేట్ పాస్‌లు ఇవ్వలేదు.",
        ["frontoffice.gatePassHelp"] = "పాస్ ఇచ్చినప్పుడు, పిల్లవాడు ముందుగా వెళ్లినట్లు ప్రధాన సంరక్షకునికి సందేశం వెళ్తుంది.",
        ["frontoffice.nameRequired"] = "సందర్శకుని పేరు నమోదు చేయండి.",
        ["frontoffice.passRequired"] = "విద్యార్థిని ఎంచుకుని, కారణం మరియు తీసుకెళ్లేవారి పేరు నింపండి.",
        ["frontoffice.passIssued"] = "గేట్ పాస్ ఇవ్వబడింది; సంరక్షకునికి తెలియజేయబడింది.",
        ["frontoffice.cannotReach"] = "సర్వర్‌ను చేరుకోలేకపోతున్నాం.",
        ["frontoffice.studentsUnavailable"] = "విద్యార్థుల జాబితా అందుబాటులో లేదు; గేట్ పాస్‌లకు ఇది అవసరం.",


        // Inventory (school store)
        ["nav.inventory"] = "స్టోర్",
        ["inventory.title"] = "పాఠశాల స్టోర్",
        ["inventory.search"] = "వస్తువులను వెతకండి",
        ["inventory.lowOnly"] = "తక్కువ నిల్వ మాత్రమే",
        ["inventory.addItem"] = "వస్తువు జోడించండి",
        ["inventory.itemName"] = "వస్తువు",
        ["inventory.category"] = "వర్గం",
        ["inventory.unit"] = "యూనిట్",
        ["inventory.reorderLevel"] = "ఈ స్థాయిలో మళ్లీ ఆర్డర్",
        ["inventory.unitCost"] = "యూనిట్ ధర",
        ["inventory.recordMovement"] = "కదలిక నమోదు",
        ["inventory.item"] = "వస్తువు",
        ["inventory.kind"] = "కదలిక",
        ["inventory.kindReceipt"] = "వచ్చింది",
        ["inventory.kindIssue"] = "ఇవ్వబడింది",
        ["inventory.kindWriteOff"] = "రద్దు చేయబడింది",
        ["inventory.kindAdjustment"] = "లెక్కించబడింది",
        ["inventory.quantity"] = "పరిమాణం",
        ["inventory.counterparty"] = "ఎవరికి / ఎవరి నుండి",
        ["inventory.adjustmentHint"] = "లెక్క నిల్వను నేరుగా నిర్ణయిస్తుంది, కలపదు.",
        ["inventory.stock"] = "ప్రస్తుత నిల్వ",
        ["inventory.onHand"] = "నిల్వ",
        ["inventory.register"] = "స్టోర్ రిజిస్టర్",
        ["inventory.balance"] = "బ్యాలెన్స్",
        ["inventory.date"] = "తేదీ",
        ["inventory.retired"] = "నిలిపివేయబడింది",
        ["inventory.noItems"] = "ఇంకా వస్తువులు లేవు.",
        ["inventory.noMovements"] = "ఇంకా నిల్వ కదలికలు లేవు.",
        ["inventory.nameRequired"] = "వస్తువు పేరు నమోదు చేయండి.",
        ["inventory.itemRequired"] = "ముందుగా వస్తువును ఎంచుకోండి.",
        ["inventory.cannotReach"] = "సర్వర్‌ను చేరుకోలేకపోతున్నాం.",


        // Shell chrome and navigation groups
        ["chrome.skipToContent"] = "ముఖ్య విషయానికి వెళ్లండి",
        ["chrome.toggleNav"] = "నావిగేషన్ మార్చండి",
        ["chrome.mainNav"] = "ప్రధాన నావిగేషన్",
        ["chrome.account"] = "ఖాతా మెనూ",
        ["chrome.language"] = "భాష మార్చండి",
        ["chrome.platform"] = "ప్లాట్‌ఫారమ్",
        ["nav.myDay"] = "నా రోజు",
        ["nav.group.overview"] = "సమగ్ర వీక్షణ",
        ["nav.group.academics"] = "విద్యా వ్యవహారాలు",
        ["nav.group.people"] = "వ్యక్తులు",
        ["nav.group.operations"] = "కార్యకలాపాలు",
        ["nav.group.communication"] = "సమాచార మార్పిడి",
        ["nav.group.finance"] = "ఆర్థిక",
        ["nav.group.administration"] = "నిర్వహణ",
        ["error.pageTitle"] = "ఈ పేజీని చూపించలేకపోయాం",
        ["error.pageBody"] = "ఈ పేజీని చూపించేటప్పుడు సమస్య ఏర్పడింది. మీ డేటాలో ఎటువంటి మార్పు జరగలేదు.",
        ["error.retry"] = "మళ్లీ ప్రయత్నించండి",

        // Students
        ["students.title"] = "విద్యార్థులు",
        ["students.export"] = "ఎగుమతి",
        ["students.import"] = "Excel నుండి దిగుమతి",
        ["students.admit"] = "విద్యార్థి ప్రవేశం",
        ["students.search"] = "పేరు లేదా ప్రవేశ సంఖ్యతో వెతకండి",
        ["students.class"] = "తరగతి",
        ["students.section"] = "సెక్షన్",
        ["students.status"] = "స్థితి",
        ["students.admissionNo"] = "ప్రవేశ సంఖ్య",
        ["students.name"] = "పేరు",
        ["students.roll"] = "రోల్",
        ["students.none"] = "విద్యార్థులు కనబడలేదు. మొదటి ప్రవేశం చేయండి.",
        ["students.importTitle"] = "Excel నుండి బల్క్ దిగుమతి",
        ["students.importHelp"] =
            "1. టెంప్లేట్ డౌన్‌లోడ్ చేయండి — అందులో ఈ పాఠశాల తరగతులు, సెక్షన్లు ఉంటాయి. " +
            "2. ఒక్కో వరుసలో ఒక విద్యార్థిని నింపండి. 3. ఫైల్ అప్‌లోడ్ చేయండి. ప్రతి వరుస " +
            "సరిగ్గా ఉంటేనే దిగుమతి జరుగుతుంది — సగం నింపిన పాఠశాల ఎప్పటికీ ఉండదు.",
        ["students.downloadTemplate"] = "టెంప్లేట్ డౌన్‌లోడ్",
        ["students.uploadTemplate"] = "నింపిన టెంప్లేట్ అప్‌లోడ్",
        ["students.importing"] = "దిగుమతి అవుతోంది…",
        ["students.rowHeader"] = "వరుస",
        ["students.problemHeader"] = "సమస్య",
    };
}
